[build]
builder = "nixpacks"

[build.nixpacksConfig]
phases.setup.nixPkgs = ["nodejs_18", "npm-9_x"]
phases.install.cmds = ["npm ci", "cd client && npm ci"]
phases.build.cmds = ["cd client && npm run build"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"